version: '3.7'

services:
  postgres:
    image: postgres:11
    container_name: vocabulary_lottery
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/var/lib/postgresql/data
